export const DESIGNATIONS = Object.freeze({
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',  
  LABTECH: 'LAB TECHNICIAN',  
});

export const SPECIALIZATIONS = Object.freeze({
  CARDIOLOGY: 'Cardiology',
  DERMATOLOGY: 'Dermatology',
  PEDIATRICS: 'Pediatrics',
  NEUROLOGY: 'Neurology',
  ORTHOPEDICS: 'Orthopedics',
  GASTROENTEROLOGY: 'Gastroenterology',
  PULMONOLOGY: 'Pulmonology',
  ENDOCRINOLOGY: 'Endocrinology',
  NEPHROLOGY: 'Nephrology',
  UROLOGY: 'Urology',
  GENERAL_SURGERY: 'General Surgery',
  OTOLARYNGOLOGY: 'Otolaryngology',
  OPHTHALMOLOGY: 'Ophthalmology',
  PSYCHIATRY: 'Psychiatry',
  ONCOLOGY: 'Oncology',
  RHEUMATOLOGY: 'Rheumatology',
  HEMATOLOGY: 'Hematology',
  OBSTETRICS_GYNECOLOGY: 'Obstetrics & Gynecology',
  RADIOLOGY: 'Radiology',
  EMERGENCY_MEDICINE: 'Emergency Medicine',
});

export const SPECIALIZATIONS_BY_ID = Object.freeze({
  1: SPECIALIZATIONS.CARDIOLOGY,
  2: SPECIALIZATIONS.DERMATOLOGY,
  3: SPECIALIZATIONS.PEDIATRICS,
  4: SPECIALIZATIONS.NEUROLOGY,
  5: SPECIALIZATIONS.ORTHOPEDICS,
  6: SPECIALIZATIONS.GASTROENTEROLOGY,
  7: SPECIALIZATIONS.PULMONOLOGY,
  8: SPECIALIZATIONS.ENDOCRINOLOGY,
  9: SPECIALIZATIONS.NEPHROLOGY,
  10: SPECIALIZATIONS.UROLOGY,
  11: SPECIALIZATIONS.GENERAL_SURGERY,
  12: SPECIALIZATIONS.OTOLARYNGOLOGY,
  13: SPECIALIZATIONS.OPHTHALMOLOGY,
  14: SPECIALIZATIONS.PSYCHIATRY,
  15: SPECIALIZATIONS.ONCOLOGY,
  16: SPECIALIZATIONS.RHEUMATOLOGY,
  17: SPECIALIZATIONS.HEMATOLOGY,
  18: SPECIALIZATIONS.OBSTETRICS_GYNECOLOGY,
  19: SPECIALIZATIONS.RADIOLOGY,
  20: SPECIALIZATIONS.EMERGENCY_MEDICINE,
});

export const SPECIALIZATION_OPTIONS = Object.freeze(
  Object.entries(SPECIALIZATIONS_BY_ID).map(([id, name]) => ({
    value: Number(id),
    label: name,
  }))
);


export const DESIGNATION_OPTIONS = Object.values(DESIGNATIONS).map(v => ({ value: v, label: v }));
